### PR TITLE
Move Species association to Measurements

### LINKED ISSUE #116: Multispecies observations mass upload
Hey @coffeejunk we just did a large upload of trait data and noticed a bug in papers with multiple species. When this data is imported every measurement is assigned to the first species in the list. For example in the most recent trait upload source White2007b has info on multiple species but every trait has been assigned to Atelomycterus baliensis. This is an issue with species being treated as an observation level metric rather than measurement level. I know we had some discussions about this in the past. Is there a way to fix this for the mass uploads, or is the way forward to enter these papers using the web template and then create new observation for each species using the same Reference?
Screen Shot 2020-07-23 at 4 11 15 PM
Screen Shot 2020-07-23 at 4 12 51 PM
Screen Shot 2020-07-23 at 4 11 51 PM

### PR DESCRIPTION
**Pull request by coffeejunk**
Fixes #116

### CODE REVIEW

**Comment by coffeejunk** [comment]
@creeas did you get a chance to test this yet? 😇

**Comment by creeas** [comment]
@coffeejunk the mass upload seems to work! Thanks! Species were split and traits assigned acordingly. I'm going to have a go with the web form next with some test data. Two small things:

1) It did allow me to upload a reference that wasn't in the ref database (see photo of resi2020). I had already created this ref in the live database so perhaps this was why it was allowed, but the metadata didn't seem to be in this deployment. So not sure if this is a real issue or not.

Screen Shot 2021-04-04 at 11 18 37 AM

2) Are the data contributors assigned only based on the login credentials used for the upload or is this info imported from the spreadsheet column AD `contributor_ID`? Would be useful this have this data from login for the webform and template for the mass uploads to easily track who contributed which data.

I'll let you know how the web form goes...thanks!

**Comment by creeas** [comment]
The web gui seems to be working as well. Entered some fake data for a real ref and seemed to work well. I tried entering data for a new ref without creating it first and it threw an error so the valid ref check works on this portion.

**Comment by coffeejunk** [comment]
> 1. It did allow me to upload a reference that wasn't in the ref database (see photo of resi2020). I had already created this ref in the live database so perhaps this was why it was allowed, but the metadata didn't seem to be in this deployment. 

You're right, the reference is only in the live database and wasn't copied over to this test deployment.

That said, it looks like you have a typo in the reference name `resi2020` instead of [`reis2020`](https://www.sharkipedia.org/references/reis2020).

> 2. […] Would be useful this have this data from login for the webform and template for the mass uploads to easily track who contributed which data.

The way it works right now is:

1. For the web from the login name is used
2. For the mass import the `contributor_id` is used (with the * that in the live DB I've changed the `contributor_id`s to the actual names of the contributors.)

I can add the name of the uploader of a mass upload to the contributors if you want to expose that name. However, if this is only for "internal tracking" we can see this on the imports overview page. Let me know what you think. 

---

If you don't have any objections, I'll go ahead and will merge & deploy this pull request. Once done, I'll delete all existing mass-uploaded trait data from the database and then you can re-import the big and small traits sheets.

**Comment by creeas** [comment]
Ha...thanks for catching the typo! Yep I think we are good to merge the pull request the once the previous uploads are deleted I can go ahead and re-import those. Thanks so much @coffeejunk !

**Pull request merged**
