### PR TITLE
Add MarineRegionsMap

### PR DESCRIPTION
**Pull request by coffeejunk**
This PR adds a map component which renders the following marine regions:
- Marine Ecoregions of the World (MEOW & PPOW)
- Longhurst Provinces
- FAO Areas

marine=regions-map

### CODE REVIEW

**Comment by coffeejunk** [comment]
You can see this in action [here](https://shark-t-staging-pr-94.herokuapp.com/trends/2).

@natpac @hkindsvater let me know what you think?

**Comment by natpac** [comment]
Wow, this is super nice Max!
Could you delete the layer 'Large Marine Ecosystems of the World' and write 'Marine Ecoregions of the World' instead of 'Pelagic Provinces of the world'. The layer that I sent you is in fact both 'Large Marine Ecosystems of the World' and 'Pelagic Provinces of the world' merged, and is the only one to keep.
Would it be possible to make the coastal and pelagic regions linked to the time-series more visible than the others? For example with a thicker edge (maybe in red) and grey hatch?
Thanks!

**Comment by coffeejunk** [comment]
@natpac FAO is now filtered down to only the major areas

**Comment by coffeejunk** [comment]
marine=regions-map

**Comment by coffeejunk** [comment]
Whoever just tried to have a look and saw an error scree, you can try again now. I forgot to run something :)

**Comment by natpac** [comment]
That is very nice Max!!

Nathan Pacoureau


Le jeu. 4 juin 2020 à 09:07, Maximilian Haack <notifications@github.com> a
écrit :

**Pull request merged**
