### PR TITLE
Updating template and restrictions

### PR DESCRIPTION
**Pull request by creeas**
Updating template and upload check csv files

### CODE REVIEW

**Review by coffeejunk — APPROVED** [review]
Looks good to me

**Comment by coffeejunk** [comment]
@creeas I saw you updated a few more CSV files, do you need me to reset the database to do some more testing?

**Comment by creeas** [comment]
Hey @coffeejunk yes that would be great!

**Comment by coffeejunk** [comment]
@creeas done. Same user & pw as before

**Comment by creeas** [comment]
10-4...thanks!

**Comment by coffeejunk** [comment]
@creeas is this ready to be reviewed/merged?

**Comment by creeas** [comment]
@coffeejunk ready for review and merging!

**Review by coffeejunk — APPROVED** [review]

**Pull request merged**
